"""PlatformIO pre-script: turn optional .env Wi-Fi defaults into a build-only header.

The header lives under the build directory (never in src/), so credentials never
enter the repository. Values are octal-escaped and are never printed.
"""
import os
import re
import string

Import("env")  # noqa: F821  (provided by PlatformIO/SCons)


def parse_value(text):
    """Value part of a .env line, dotenv style. None if a quote is not closed or
    anything but a comment follows the closing quote."""
    text = text.strip()
    if text[:1] in ('"', "'"):
        quote, out, i = text[0], [], 1
        while i < len(text):
            ch = text[i]
            if quote == '"' and ch == "\\" and text[i + 1:i + 2] in ('"', "\\"):
                out.append(text[i + 1])   # \" and \\ are escapes inside double quotes
                i += 2
                continue
            if ch == quote:
                rest = text[i + 1:].strip()
                return "".join(out) if not rest or rest.startswith("#") else None
            out.append(ch)
            i += 1
        return None
    # Unquoted: a "#" after whitespace starts a comment ("pa#ss" stays whole).
    return re.split(r"\s#", text, maxsplit=1)[0].rstrip()


def parse_env_file(path):
    """{key: value} and the keys whose value could not be parsed."""
    values, bad = {}, []
    if not os.path.isfile(path):
        return values, bad
    # utf-8-sig also reads files that start with a BOM (Windows PowerShell 5.1
    # writes one with "-Encoding UTF8").
    with open(path, encoding="utf-8-sig") as fh:
        for raw in fh:
            line = raw.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, val = line.split("=", 1)
            key = key.strip()
            if key.startswith("export "):
                key = key[len("export "):].strip()
            parsed = parse_value(val)
            if parsed is None:
                bad.append(key)
            else:
                values[key] = parsed
    return values, bad


def is_placeholder(text):
    return text.startswith("<") and text.endswith(">")


def c_literal(text):
    out = []
    for byte in text.encode("utf-8"):
        # Only ASCII letters/digits pass through; everything else (including
        # UTF-8 bytes >= 0x80, which str.isalnum() would accept) is escaped.
        ch = chr(byte)
        out.append(ch if byte < 0x80 and ch.isalnum() else "\\%03o" % byte)
    return '"' + "".join(out) + '"'


project_dir = env.subst("$PROJECT_DIR")  # noqa: F821
build_dir = env.subst("$BUILD_DIR")  # noqa: F821
values, bad = parse_env_file(os.path.join(project_dir, ".env"))
ssid = values.get("WIFI_SSID", "")
password = values.get("WIFI_PASSWORD", "")
pass_len = len(password.encode("utf-8"))
bad = [key for key in bad if key in ("WIFI_SSID", "WIFI_PASSWORD")]
problem = None
if bad:
    problem = "unclosed quote or text after the closing quote in %s" % ", ".join(bad)
elif is_placeholder(ssid) or is_placeholder(password):
    problem = "still contains a <placeholder>"
elif len(ssid.encode("utf-8")) > 32:
    problem = "WIFI_SSID longer than 32 bytes"
elif password and not (8 <= pass_len <= 63 or (pass_len == 64 and all(c in string.hexdigits for c in password))):
    # WPA2: 8-63 character passphrase or the key as 64 hex digits; empty = open network
    problem = "WIFI_PASSWORD must be empty (open network), 8-63 characters or 64 hex digits"
elif password and not ssid:
    problem = "WIFI_PASSWORD set but WIFI_SSID empty"
if problem:
    print("pio_env: .env ignored: %s" % problem)
    ssid, password = "", ""

gen_dir = os.path.join(build_dir, "generated")
os.makedirs(gen_dir, exist_ok=True)
header = os.path.join(gen_dir, "wifi_default.h")
content = (
    "// Generated by scripts/pio_env.py from .env - do not commit\n"
    "#pragma once\n"
    "#define WIFI_DEFAULT_SSID %s\n"
    "#define WIFI_DEFAULT_PASSWORD %s\n" % (c_literal(ssid), c_literal(password))
)
old = None
if os.path.isfile(header):
    with open(header, encoding="utf-8") as fh:
        old = fh.read()
if old != content:
    with open(header, "w", encoding="utf-8") as fh:
        fh.write(content)

env.Append(CPPPATH=[gen_dir])  # noqa: F821
print("pio_env: Wi-Fi default from .env: %s" % ("yes" if ssid else "no"))
