"""PlatformIO pre-script: turn optional .env Wi-Fi defaults into a build-only header.

The header lives under the build directory (never in src/), so credentials never
enter the repository. Values are octal-escaped and are never printed.
"""
import os

Import("env")  # noqa: F821  (provided by PlatformIO/SCons)


def parse_env_file(path):
    values = {}
    if not os.path.isfile(path):
        return values
    with open(path, encoding="utf-8") as fh:
        for raw in fh:
            line = raw.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, val = line.split("=", 1)
            key = key.strip()
            val = val.strip()
            if len(val) >= 2 and val[0] == val[-1] == '"':
                # dotenv style: \" and \\ are escapes inside double quotes
                val = val[1:-1].replace("\\\\", "\0").replace('\\"', '"').replace("\0", "\\")
            elif len(val) >= 2 and val[0] == val[-1] == "'":
                val = val[1:-1]
            values[key] = val
    return values


def is_placeholder(text):
    return text.startswith("<") and text.endswith(">")


def c_literal(text):
    out = []
    for byte in text.encode("utf-8"):
        # Only ASCII letters/digits pass through; everything else (including
        # UTF-8 bytes >= 0x80, which str.isalnum() would accept) is escaped.
        ch = chr(byte)
        out.append(ch if byte < 0x80 and ch.isalnum() else "\\%03o" % byte)
    return '"' + "".join(out) + '"'


project_dir = env.subst("$PROJECT_DIR")  # noqa: F821
build_dir = env.subst("$BUILD_DIR")  # noqa: F821
values = parse_env_file(os.path.join(project_dir, ".env"))
ssid = values.get("WIFI_SSID", "")
password = values.get("WIFI_PASSWORD", "")
problem = None
if is_placeholder(ssid) or is_placeholder(password):
    problem = "still contains a <placeholder>"
elif len(ssid.encode("utf-8")) > 32:
    problem = "WIFI_SSID longer than 32 bytes"
elif password and not 8 <= len(password.encode("utf-8")) <= 64:
    # WPA2: 8-63 character passphrase or a 64-digit hex PSK; empty = open network
    problem = "WIFI_PASSWORD must be empty (open network) or 8-64 characters"
elif password and not ssid:
    problem = "WIFI_PASSWORD set but WIFI_SSID empty"
if problem:
    print("pio_env: .env ignored: %s" % problem)
    ssid, password = "", ""

gen_dir = os.path.join(build_dir, "generated")
os.makedirs(gen_dir, exist_ok=True)
header = os.path.join(gen_dir, "wifi_default.h")
content = (
    "// Generated by scripts/pio_env.py from .env - do not commit\n"
    "#pragma once\n"
    "#define WIFI_DEFAULT_SSID %s\n"
    "#define WIFI_DEFAULT_PASSWORD %s\n" % (c_literal(ssid), c_literal(password))
)
old = None
if os.path.isfile(header):
    with open(header, encoding="utf-8") as fh:
        old = fh.read()
if old != content:
    with open(header, "w", encoding="utf-8") as fh:
        fh.write(content)

env.Append(CPPPATH=[gen_dir])  # noqa: F821
print("pio_env: Wi-Fi default from .env: %s" % ("yes" if ssid else "no"))
